services:
  s3:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    container_name: s3
    command: server --console-address ":9001" /data
    env_file:
      - minio.env
    ports:
      - "9001:9001"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  
  dwh:
    image: "postgres:14"
    container_name: dwh
    env_file:
      - "dwh.env"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      retries: 2
      interval: 5s
      timeout: 5s

#  Airflow section start
  postgres:
    image: postgres:14
    container_name: airflow_postgres
    env_file:
      - airflow.env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    restart: always

  scheduler:
    build: .
    command: scheduler
    container_name: airflow_scheduler
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      s3:
        condition: service_healthy
    env_file:
      - airflow.env
    environment:
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      #- ./.aws/:/home/airflow/.aws:ro
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  webserver:
    build: .
    container_name: airflow_webserver
    entrypoint: bash ./scripts/entrypoint.sh
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      s3:
        condition: service_healthy
    env_file:
      - airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      #- ./.aws/:/home/airflow/.aws:ro

    user: "${AIRFLOW_UID:-50000}:0"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
#  Airflow section end

volumes:
  postgres-db-volume: